In [3]:
import numpy as np
print(np.__version__)
np.__config__.show()

2.4.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-7so2u9ys/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-7so2u9ys/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.31.dev  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.31.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-7so2u9ys/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-7so2u9ys/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas conf

In [5]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
# 创建一个向量，范围是 2 - 22
Z = np.arange(21) + 2
print(Z)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [14]:
# 创建一个三维矩阵，数据为 0 - 8
Z = np.arange(9)
Z = Z.reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
# 找出向量中所有非零的索引
Z = np.arange(21)
print(Z.nonzero())

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20]),)


In [16]:
# 声明一个单位矩阵
Z = np.eye(10)
print(Z)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [25]:
# 声明一个 5x5 矩阵，对角线上下四个元素的值分别为 1、2、3、4
Z = np.zeros((5, 5))
V = np.arange(4) + 1
Z += np.diag(V, 1)
Z += np.diag(V, -1)
print(Z)

[[0. 1. 0. 0. 0.]
 [1. 0. 2. 0. 0.]
 [0. 2. 0. 3. 0.]
 [0. 0. 3. 0. 4.]
 [0. 0. 0. 4. 0.]]
[1 2 3 4]


In [27]:
# 声明一个 10 * 10 * 10 矩阵，填入随机值
Z = np.random.random((10, 10, 10))
print(Z)

[[[4.42023754e-01 3.08933370e-01 8.10272069e-01 1.59023520e-01
   9.94142346e-01 3.98182581e-01 4.43995342e-01 4.47285947e-01
   3.44449205e-01 7.39092380e-01]
  [3.03876298e-01 3.44293126e-01 3.38197113e-01 7.47082143e-01
   9.17403614e-01 6.98150313e-01 6.44138469e-01 8.38104051e-02
   4.47440282e-01 2.72973419e-01]
  [3.48335140e-01 8.75947258e-01 6.64098996e-01 7.08760804e-01
   8.38010894e-01 7.35725839e-01 3.15527602e-02 3.92189773e-01
   8.33284947e-02 5.58296569e-01]
  [3.49510011e-01 8.65311212e-01 7.94466439e-01 1.06782741e-01
   5.63904593e-02 4.09560092e-01 1.72888312e-01 1.50065214e-01
   8.65223966e-02 7.34924120e-01]
  [8.77447028e-01 7.25174103e-01 5.11781235e-01 2.70401755e-01
   5.64356765e-01 6.16788193e-01 5.04578012e-01 8.16072577e-01
   9.97369802e-01 9.08636986e-01]
  [3.55211836e-01 1.30722011e-01 3.92075490e-02 9.73959893e-01
   6.35192989e-01 7.94033973e-01 5.98474327e-01 4.44435323e-01
   4.65000426e-02 8.28028037e-01]
  [9.89885578e-02 1.86264727e-01 8.89493