In [37]:
import numpy as np

Z = np.array([[0, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0],
              [0, 1, 0, 1, 0, 0],
              [0, 0, 1, 1, 0, 0],
              [0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0]], dtype=int)


In [38]:
# 查找邻居
N = np.zeros(Z.shape, dtype=int)
N[1:-1, 1:-1] = Z[:-2, :-2] + Z[:-2, 1:-1] + Z[:-2, 2:] + \
                Z[1:-1, :-2] + Z[1:-1, 2:] + \
                Z[2:, :-2] + Z[2:, 1:-1] + Z[2:, 2:]

In [39]:
def show(Z):
    for row in Z[1:-1]:
        print(row[1:-1])
    print()

In [40]:
show(Z)
show(N)

[0 0 1 0]
[1 0 1 0]
[0 1 1 0]
[0 0 0 0]

[1 3 1 2]
[1 5 3 3]
[2 3 2 2]
[1 2 2 1]



In [41]:

for _ in range(3):
    N[1:-1, 1:-1] = Z[:-2, :-2] + Z[:-2, 1:-1] + Z[:-2, 2:] + \
                    Z[1:-1, :-2] + Z[1:-1, 2:] + \
                    Z[2:, :-2] + Z[2:, 1:-1] + Z[2:, 2:]

    # 将数据铺开成一维数组，对一位数组的修改会反映在多维度
    N_ = N.ravel()
    Z_ = Z.ravel()

    R1 = np.argwhere((Z_ == 1) & ((N_ < 2) | (N_ > 3)))
    R2 = np.argwhere((Z_ == 0) & (N_ == 3))

    Z_[R1] = 0
    Z_[R2] = 1

In [42]:
show(Z)

[0 0 0 0]
[0 1 0 1]
[0 0 1 1]
[0 0 1 0]



In [43]:
for _ in range(1):
    N = (Z[:-2, :-2] + Z[:-2, 1:-1] + Z[:-2, 2:] +
         Z[1:-1, :-2] + Z[1:-1, 2:] +
         Z[2:, :-2] + Z[2:, 1:-1] + Z[2:, 2:])

    birth = (N == 3) & (Z[1:-1, 1:-1] == 0)
    alive = ((N == 3) | (N == 2)) & (Z[1:-1, 1:-1] == 1)

    Z[...] = 0
    Z[1:-1, 1:-1][birth | alive] = 1

In [44]:
show(Z)

[0 0 0 0]
[0 0 0 1]
[0 1 0 1]
[0 0 1 1]

